#!/bin/bash

dt=`date +%Y-%m-%d-%s`

DEPLOY_PATH=$(dirname $0)

if [[ ! -d DEPLOY_PATH ]]; then
  echo "ERROR: $DEPLOY_PATH is not a directory."
  exit 1
fi

log_file="$DEPLOY_PATH/logs/start.${dt}"


ulimit -n 500000
nohup $DEPLOY_PATH/cockroach $@ --background &>$log_file </dev/null
